import type { MetadataRoute } from "next";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://sys.parvsharma.in";

export default function sitemap(): MetadataRoute.Sitemap {
    const now = new Date();

    const staticPages = [
        { url: "", priority: 1.0, changeFrequency: "weekly" as const },
        { url: "/rate-limiting", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/resilience", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/caching", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/load-balancing", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/messaging", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/coordination", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/consistency", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/consensus", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/storage", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/observability", priority: 0.9, changeFrequency: "weekly" as const },
        { url: "/security", priority: 0.9, changeFrequency: "weekly" as const },
    ];

    const conceptPages = [
        "/rate-limiting/fixed-window-counter",
        "/rate-limiting/sliding-window-log",
        "/rate-limiting/sliding-window-counter",
        "/rate-limiting/token-bucket",
        "/rate-limiting/leaky-bucket",
        "/resilience/circuit-breaker",
        "/resilience/retry-with-backoff",
        "/resilience/timeout-wrapper",
        "/resilience/bulkhead",
        "/resilience/hedged-requests",
        "/resilience/fallback-strategy",
        "/caching/lru-cache",
        "/caching/lfu-cache",
        "/caching/ttl-cache",
        "/caching/cache-aside",
        "/caching/write-through-back",
        "/caching/cache-stampede",
        "/caching/bloom-filter",
        "/load-balancing/round-robin",
        "/load-balancing/weighted-round-robin",
        "/load-balancing/least-connections",
        "/load-balancing/ip-hashing",
        "/load-balancing/consistent-hashing",
        "/messaging/in-memory-queue",
        "/messaging/pub-sub-broker",
        "/messaging/at-most-once",
        "/messaging/at-least-once",
        "/messaging/dead-letter-queue",
        "/messaging/consumer-groups",
        "/messaging/partitioned-log",
        "/coordination/distributed-lock",
        "/coordination/leader-election",
        "/coordination/heartbeat-monitor",
        "/coordination/service-registry",
        "/coordination/service-discovery",
        "/consistency/primary-replica",
        "/consistency/read-write-quorum",
        "/consistency/vector-clocks",
        "/consistency/crdt-counters",
        "/consensus/two-phase-commit",
        "/consensus/three-phase-commit",
        "/consensus/simplified-raft",
        "/storage/key-value-store",
        "/storage/append-only-log",
        "/storage/write-ahead-log",
        "/storage/sstable",
        "/storage/lsm-tree",
        "/observability/metrics-collector",
        "/observability/histogram",
        "/observability/structured-logger",
        "/observability/trace-id-propagation",
        "/security/jwt-validation",
        "/security/api-key-validation",
        "/security/idempotency-key",
        "/security/hmac-verification",
    ];

    return [
        ...staticPages.map((page) => ({
            url: `${SITE_URL}${page.url}`,
            lastModified: now,
            changeFrequency: page.changeFrequency,
            priority: page.priority,
        })),
        ...conceptPages.map((path) => ({
            url: `${SITE_URL}${path}`,
            lastModified: now,
            changeFrequency: "monthly" as const,
            priority: 0.8,
        })),
    ];
}
